// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fimgalqlsezgxqbmktpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbWdhbHFsc2V6Z3hxYm1rdHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjkyMTEsImV4cCI6MjA2NzUwNTIxMX0.Wg_X2gExD4wlaBQ42QAQ4ERs4kJVHAk2ZNA6IOd4woU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Re-export functions from the dynamic config utility
export { invokeEdgeFunction, getStorageUrl, getWebhookUrl, supabaseBase } from '@/utils/supabaseConfigClient';